# Generated by Django 2.2.14 on 2020-08-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='thois is an amazing shit'),
            preserve_default=False,
        ),
    ]
